import turtle

fred = turtle.Turtle()
fred.forward(10)
fred.left(135)
fred.forward(15)
fred.pensize(2)
fred.right(45)
fred.forward(50)
fred.write("hello")
fred.right(45)
fred.forward(50)
fred.write("how")
fred.right(45)
fred.forward(50)
fred.write("are")
fred.right(45)
fred.forward(50)
fred.write("you")
fred.right(45)
fred.forward(50)
fred.write("my")
fred.right(45)
fred.forward(50)
fred.write("friend")
fred.right(45)
fred.forward(50)
fred.write("!!!!")
fred.right(45)
fred.forward(50)
fred.write("!!!!")
turtle.done()
